---
title: "BBS Analysis"
output: html_document
---


```{r, echo=FALSE}

library(tidyverse)
library(dplyr)
library(FD)
library(spData)
library(sf)
library(tmap)

piggyback::pb_download(repo = "karinorman/functional_diversity")

load("./data/trait.rda")
load("./data/bbs.rda")


min_year = 2006 #define the minimum year of sampling to include

p <- st_crs(wkt='PROJCS["USA_Contiguous_Albers_Equal_Area_Conic",
    GEOGCS["GCS_North_American_1983",
            DATUM["North_American_Datum_1983",
            SPHEROID["GRS_1980",6378137,298.257222101]],
            PRIMEM["Greenwich",0],
            UNIT["Degree",0.017453292519943295]],
            PROJECTION["Albers_Conic_Equal_Area"],
            PARAMETER["False_Easting",0],
            PARAMETER["False_Northing",0],
            PARAMETER["longitude_of_center",-96],
            PARAMETER["Standard_Parallel_1",29.5],
            PARAMETER["Standard_Parallel_2",45.5],
            PARAMETER["latitude_of_center",37.5],
            UNIT["Meter",1],
            AUTHORITY["EPSG","102003"]]')

```

```{r}
bbs_site_FD <- get_complete_site_data()


#Simulate null model for one region
n_rockies_FD <- filter(bbs_site_FD, region == "NORTHERN ROCKIES")
n_rockies <- bbs %>% 
  filter(year > min_year & site_id %in% unique(n_rockies_FD$site_id))

species_pool <- unique(n_rockies$scientific)

get_sample_fd <- function(x, ...){
  samp_trait_mat <- get_trait_matrix(sample(species_pool, x))
  samp_species <- rownames(samp_trait_mat)
  sample_FD <- dbFD(x = samp_trait_mat, ...)
  #return(c(richness = x, head(sample_FD, -1))) #remove last element, which is the CWM for each trait - maybe add back in later?
  return(list("species" = samp_species, "FD" = head(sample_FD, -1)))
}

#test_sim <- plyr::ldply(100:length(species_pool), get_sample_fd(calc.FRic = FALSE)$species) #would work if dbFD didn't error out

FDdf <- data.frame()
rich_vals <- c()
#for loop option, still need to add database for iterative storage
for(i in 106:length(species_pool)){
  possibleError <- tryCatch(
    samp_fd <- get_sample_fd(i),
    error=function(e)e
  )
  if(inherits(possibleError, "error")) next
  
  #rich_vals <- c(rich_vals, i)
  FDdf <- rbind(FDdf, samp_fd$FD)
}

#recalculate broken case from for loop ^^^
test_trait_mat <- get_trait_matrix(samp_fd$species)
test_samp_fd <- dbFD(x = test_trait_mat)


#preliminary plot of null curve
FDdf %>% ggplot(aes(x = nbsp, y = FDiv)) + geom_smooth() +
  theme_classic()

```

